[2025-10-20T13:23:40.033+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T13:23:43.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [queued]>
[2025-10-20T13:23:45.088+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [queued]>
[2025-10-20T13:23:45.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-20T13:23:46.651+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_task> on 2025-10-20 13:18:29+00:00
[2025-10-20T13:23:46.894+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_etl', 'store_task', 'manual__2025-10-20T13:18:29+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmpg_w5445k']
[2025-10-20T13:23:46.900+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask store_task
[2025-10-20T13:23:46.901+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T13:23:46.902+0000] {standard_task_runner.py:64} INFO - Started process 265 to run task
[2025-10-20T13:23:59.892+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [running]> on host 7c69cd8a671d
[2025-10-20T13:24:16.942+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_etl' AIRFLOW_CTX_TASK_ID='store_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T13:18:29+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T13:18:29+00:00'
[2025-10-20T13:24:16.945+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T13:24:19.898+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/stock_etl_dag.py:97 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2025-10-20T13:24:19.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T13:24:19.986+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 103, in store_data
    raise ValueError("AIVEN_DB_URL not set in environment variables")
ValueError: AIVEN_DB_URL not set in environment variables
[2025-10-20T13:24:27.025+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_etl, task_id=store_task, run_id=manual__2025-10-20T13:18:29+00:00, execution_date=20251020T131829, start_date=20251020T132343, end_date=20251020T132427
[2025-10-20T13:24:28.716+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task store_task (AIVEN_DB_URL not set in environment variables; 265)
[2025-10-20T13:24:30.239+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T13:24:33.243+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T13:24:33.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
