[2025-10-20T13:30:15.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-20T13:30:20.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [queued]>
[2025-10-20T13:30:25.959+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [queued]>
[2025-10-20T13:30:25.960+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-20T13:30:28.020+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_task> on 2025-10-20 13:18:29+00:00
[2025-10-20T13:30:28.053+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_etl', 'store_task', 'manual__2025-10-20T13:18:29+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmp1f7jgp57']
[2025-10-20T13:30:28.061+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask store_task
[2025-10-20T13:30:28.061+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-20T13:30:28.062+0000] {standard_task_runner.py:64} INFO - Started process 316 to run task
[2025-10-20T13:30:40.072+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_etl.store_task manual__2025-10-20T13:18:29+00:00 [running]> on host 7c69cd8a671d
[2025-10-20T13:31:01.633+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_etl' AIRFLOW_CTX_TASK_ID='store_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-20T13:18:29+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-20T13:18:29+00:00'
[2025-10-20T13:31:01.637+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-20T13:31:05.086+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/stock_etl_dag.py:97 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2025-10-20T13:31:05.163+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-20T13:31:05.166+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 103, in store_data
    raise ValueError("AIVEN_DB_URL not set in environment variables")
ValueError: AIVEN_DB_URL not set in environment variables
[2025-10-20T13:31:08.016+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_etl, task_id=store_task, run_id=manual__2025-10-20T13:18:29+00:00, execution_date=20251020T131829, start_date=20251020T133020, end_date=20251020T133108
[2025-10-20T13:31:09.327+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task store_task (AIVEN_DB_URL not set in environment variables; 316)
[2025-10-20T13:31:09.420+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-20T13:31:11.794+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-20T13:31:12.051+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
