[2025-10-15T00:05:13.918+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-15T00:05:13.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T00:05:14.006+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [queued]>
[2025-10-15T00:05:14.007+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-10-15T00:05:14.037+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-10-14 00:00:00+00:00
[2025-10-15T00:05:14.055+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_market_etl', 'extract_task', 'scheduled__2025-10-14T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/stock_etl_dag.py', '--cfg-path', '/tmp/tmpqps0lks8']
[2025-10-15T00:05:14.061+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask extract_task
[2025-10-15T00:05:14.061+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3457) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-15T00:05:14.062+0000] {standard_task_runner.py:64} INFO - Started process 3459 to run task
[2025-10-15T00:05:14.177+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_market_etl.extract_task scheduled__2025-10-14T00:00:00+00:00 [running]> on host 9d4269c8615b
[2025-10-15T00:05:14.648+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_market_etl' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-14T00:00:00+00:00'
[2025-10-15T00:05:14.650+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-15T00:05:14.674+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-15T00:05:14.674+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_etl_dag.py", line 20, in extract_stock_data
    raise ValueError("API_KEY environment variable is not set")
ValueError: API_KEY environment variable is not set
[2025-10-15T00:05:14.689+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_market_etl, task_id=extract_task, run_id=scheduled__2025-10-14T00:00:00+00:00, execution_date=20251014T000000, start_date=20251015T000513, end_date=20251015T000514
[2025-10-15T00:05:14.709+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task extract_task (API_KEY environment variable is not set; 3459)
[2025-10-15T00:05:14.760+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-15T00:05:14.814+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-15T00:05:14.823+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
